sanitize some unescaped HTML from CDP
ChromeDevTools/debugger-protocol-viewer pull request #202
Opened 2023-07-19 18:31 UTC by paulirish

The actual fixes this makes in the generated HTML: https://gist.github.com/paulirish/f7f86e982487a23f494b6c834841743f

2023-07-19 22:09 UTC, thiagowfx requested changes

2023-07-19 22:09 UTC, thiagowfx commented on pages/domainGenerator.js
> +    .replaceAll('&amp;gt', '&gt;')  //  IO.StreamHandle (actual typo in desc)
Better fix the typo right at the source then.

2023-07-19 22:09 UTC, thiagowfx commented on pages/domainGenerator.js
> +  const html = marked(mdText);
```suggestion
  mdText = mdText.replaceAll('<', '&lt;'); // protect against some naked `<script>` and `<label>` and `<input>` in the JSON
  const html = marked(mdText);
```

2023-07-19 22:09 UTC, thiagowfx commented on pages/domainGenerator.js
> +    .replaceAll('&lt;p&gt;Note that', '<p>Note that').replaceAll('their child nodes.&lt;/p&gt;</p>', 'their child nodes.</p></p>') // DOM domain description
This one also looks odd. Better fix at the source

2023-07-20 19:28 UTC, paulirish commented on pages/domainGenerator.js
> +    .replaceAll('&amp;gt', '&gt;')  //  IO.StreamHandle (actual typo in desc)
yeah this one was extra dumb.

well.. i fixed allllllll things at the source ... 
https://chromium-review.googlesource.com/c/chromium/src/+/4704893

after it lands ill revise this PR to be more minimal, probably

2023-07-21 08:23 UTC, thiagowfx commented on pages/domainGenerator.js
> +    .replaceAll('&amp;gt', '&gt;')  //  IO.StreamHandle (actual typo in desc)
Sounds good

2023-07-24 22:52 UTC, paulirish commented on pages/domainGenerator.js
> +    .replaceAll('&amp;gt', '&gt;')  //  IO.StreamHandle (actual typo in desc)
updated. ptal

2023-07-25 09:51 UTC, thiagowfx approved these changes

2023-07-25 09:52 UTC, merged